version: "1"

#volumes:
#  mongodb_volume:

services:
  fastapi:
    build: FastAPI/
    restart: always
    ports:
      - 8000:8000
    environment:
      - TZ=Europe/Minsk
#      - MONGO_DB_ADDR=mongodb
#      - MONGO_DB_PORT=27017

#  mongodb:
#    image: mongo:latest
#    volumes:
#      - mongodb_volume:/data/db
#    restart: always
